// Writes the site's security headers into ../amplify.yml, from the same
// source next.config.ts uses (security-headers.mjs), so the two can't drift.
//
//   npm run headers:amplify             rewrite the block in amplify.yml
//   npm run headers:amplify -- --check  exit 1 if amplify.yml is out of date
//
// connect-src needs real origins. Set them when you know them:
//
//   NEXT_PUBLIC_API_BASE=https://api.example.org \
//   NEXT_PUBLIC_UPLOAD_ORIGIN=https://my-bucket.s3.amazonaws.com \
//   npm run headers:amplify
//
// Until then the block allows the two AWS services the app is deployed on
// (App Runner for the API, S3 for resume uploads) by wildcard. That is wider
// than it should be at launch: narrow it with the command above.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { originOf, securityHeaders } from "../security-headers.mjs";

export const LAUNCH_DEFAULT_CONNECT = ["https://*.awsapprunner.com", "https://*.amazonaws.com"];
const BEGIN = "    # BEGIN security headers (generated by frontend/scripts/amplify-headers.mjs; do not edit by hand)";
const END = "    # END security headers";

const file = fileURLToPath(new URL("../../amplify.yml", import.meta.url));

export function block(env = process.env) {
  const exact = [originOf(env.NEXT_PUBLIC_API_BASE), originOf(env.NEXT_PUBLIC_UPLOAD_ORIGIN)].filter(Boolean);
  const headers = securityHeaders({ dev: false, connect: exact.length ? exact : LAUNCH_DEFAULT_CONNECT });
  const yaml = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  return [
    BEGIN,
    exact.length
      ? `    # connect-src is pinned to: ${exact.join(" ")}`
      : "    # connect-src uses launch defaults (any App Runner or AWS host). Pin it before launch.",
    "    customHeaders:",
    "      - pattern: '**/*'",
    "        headers:",
    ...headers.flatMap((h) => [`          - key: ${yaml(h.key)}`, `            value: ${yaml(h.value)}`]),
    END,
  ].join("\n");
}

export function current() {
  const text = readFileSync(file, "utf8");
  const a = text.indexOf(BEGIN);
  const b = text.indexOf(END);
  return { text, found: a !== -1 && b !== -1 ? text.slice(a, b + END.length) : null, a, b };
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const want = block();
  const { text, found, a, b } = current();
  if (process.argv.includes("--check")) {
    if (found === want) {
      console.log("amplify.yml security headers are up to date.");
    } else {
      console.error("amplify.yml security headers are out of date. Run: npm run headers:amplify");
      process.exit(1);
    }
  } else {
    const next = found ? text.slice(0, a) + want + text.slice(b + END.length) : text.replace(/\n*$/, "\n") + want + "\n";
    writeFileSync(file, next);
    console.log(found === want ? "amplify.yml already up to date." : "amplify.yml updated.");
  }
}
