// Writes the site's security headers into ../amplify.yml, from the one
// definition in security-headers.mjs.
//
//   npm run headers:amplify             rewrite the block in amplify.yml
//   npm run headers:amplify -- --check  exit 1 if amplify.yml is out of date
//   npm run headers:amplify -- --print  print the block in the format of a
//                                       customHttp.yml file, and change nothing
//
// The headers name no domain, so the same block is right for every
// environment. The exact origins the site may call are in the policy that
// each page carries (see security-headers.mjs), which is written at build
// time from the environment variables.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { securityHeaders } from "../security-headers.mjs";

const BEGIN = "    # BEGIN security headers (generated by frontend/scripts/amplify-headers.mjs; do not edit by hand)";
const END = "    # END security headers";
const file = fileURLToPath(new URL("../../amplify.yml", import.meta.url));

const yaml = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

/** The customHeaders entry, indented for its place under `applications:`. */
function entries(indent) {
  // '**' is the pattern AWS uses in its own security headers example.
  return [
    `${indent}customHeaders:`,
    `${indent}  - pattern: '**'`,
    `${indent}    headers:`,
    ...securityHeaders({ dev: false }).flatMap((h) => [
      `${indent}      - key: ${yaml(h.key)}`,
      `${indent}        value: ${yaml(h.value)}`,
    ]),
  ];
}

const block = () => [BEGIN, ...entries("    "), END].join("\n");

const want = block();
const text = readFileSync(file, "utf8");
const a = text.indexOf(BEGIN);
const b = text.indexOf(END);
const found = a !== -1 && b !== -1 ? text.slice(a, b + END.length) : null;

if (process.argv.includes("--print")) {
  console.log(["applications:", "  - appRoot: frontend", ...entries("    ")].join("\n"));
} else if (process.argv.includes("--check")) {
  if (found === want) {
    console.log("amplify.yml security headers are up to date.");
  } else {
    console.error("amplify.yml security headers are out of date. Run: npm run headers:amplify");
    process.exit(1);
  }
} else {
  const next = found ? text.slice(0, a) + want + text.slice(b + END.length) : text.replace(/\n*$/, "\n") + want + "\n";
  writeFileSync(file, next);
  console.log(found === want ? "amplify.yml already up to date." : "amplify.yml updated.");
}
